# Generated by Django 3.1.1 on 2022-08-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images",
                to="portfolio.section",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="sections",
                to="portfolio.page",
            ),
        ),
    ]
