# Generated by Django 5.2.4 on 2025-07-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_arbitraryfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="external_url",
            field=models.TextField(
                blank=True,
                help_text="This is only useful if mode is external",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="mode",
            field=models.CharField(
                choices=[("page", "Internal page"), ("external", "External page")],
                default="page",
                help_text="Select if the page is internal, redirect or external link",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="show_in_nav",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="If false, the page will not show in the nav",
            ),
        ),
    ]
