# Generated by Django 5.2.4 on 2025-07-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_page_external_url_page_mode_page_show_in_nav"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="image_position",
            field=models.CharField(
                choices=[("top", "Top"), ("bottom", "Bottom")],
                default="bottom",
                help_text="Set the images on top or on bottom .",
                max_length=10,
            ),
        ),
    ]
