# Generated by Django 5.2.4 on 2025-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_section_image_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="display_style",
            field=models.CharField(
                choices=[("rect", "Rect"), ("round", "Circular")],
                default="rect",
                help_text="Defines if the image is circular or rectangular.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="image_position",
            field=models.CharField(
                choices=[("top", "Top"), ("bottom", "Bottom"), ("none", "None")],
                default="none",
                help_text="Set the images on top or on bottom .",
                max_length=10,
            ),
        ),
    ]
